### PR TITLE
Multiple partial paths support, again

### PR DESCRIPTION
**Pull request by patuf**
This is, with some insignificant changes, the cherrypicked code from @pflannery that adds support for multiple partial paths. It was merged from pull request #14 in commit 5086e1, into what seems to be a dead branch now and never merged to master. I'm using it actively now and it seems to work without issues.

### CODE REVIEW

**Comment by balupton** [comment]
LGTM, added you as a maintainer. When you are ready to do the release, follow the details in the `CONTRIBUTING.md`, the `npm run our:release` will deploy to travis and that should do the npm publish if everything is good.

**Comment by patuf** [comment]
After minor compatibility change in package.json (added double quotes around $MESSAGE, bc my bash wouldn't understand it without them), it packaged successfully.

**Comment by patuf** [comment]
@balupton I think I'll need some help with the Travis, though, it seems to be failing for some obscure to me reason:
/home/travis/.travis/job_stages: eval: line 114: syntax error: unexpected end of file

**Comment by Aglezabad** [comment]
You must include the Travis scripts inside your project. Actually, using
remote scripts in Travis causes unexpected failures. That's because I have
failures doing the same thing as official Docpad plugins.

Best regards.

2017-11-06 14:11 GMT+01:00 patuf <notifications@github.com>:

**Comment by patuf** [comment]
@Aglezabad, I found the culprit: https://github.com/balupton/awesome-travis/issues/2

**Comment by Aglezabad** [comment]
Thank you. I will check if I can get successful results.

**Pull request closed without merging**
